version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./conf/php
    volumes:
      - ./www:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: my_password
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: